name: "Auto fork sync"

on:
  # schedule:
  #   - cron: '0 7 * * 1,4'
  #   # scheduled at 07:00 every Monday and Thursday

  workflow_dispatch: # click the button on Github repo!

jobs:
  sync_with_upstream:
    runs-on: ubuntu-latest
    name: Sync master with upstream latest

    steps:
      # Step 1: run a standard checkout action, provided by github
      - name: Checkout master
        uses: actions/checkout@v2
        with:
          ref: master
          # submodules: 'recursive'     ### may be needed in your situation

      # Step 2: run this sync action - specify the upstream repo, upstream branch to sync with, and target sync branch
      - name: Pull (Fast-Forward) upstream changes
        id: sync
        uses: aormsby/Fork-Sync-With-Upstream-action@v2.1
        with:
          upstream_repository: cloud-ru-tech/figma-tokens
          upstream_branch: master
          target_branch: master
          git_pull_args: --ff-only # optional arg use, defaults to simple 'pull'

      # Step 3: Display a message if 'sync' step had new commits (simple test)
      - name: Check for new commits
        if: steps.sync.outputs.has_new_commits
        run: echo "There were new commits."

      # Step 4: Print a helpful timestamp for your records (not required, just nice)
      - name: Timestamp
        run: date
  rebase:
    needs: [sync_with_upstream]
    runs-on: ubuntu-latest
    env:
      HUSKY: 0
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: "brand"

      - name: Rebase 'brand' from 'master'
        run: |
          git config --global user.email "example@expample.com"
          git config --global user.name "example-user"
          git rebase origin/master
          git push origin brand --force-with-lease
        shell: bash
