name: Release preview

on: workflow_dispatch

jobs:
  preview:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Publish preview
        env:
          NPM_TOKEN: ${{ secrets.CI_NPM_TOKEN }}
        run: |
          git config --global user.email "example@expample.com"
          git config --global user.name "example-user"
          npm config --global set //registry.npmjs.org/:_authToken=${{ secrets.CI_NPM_TOKEN }}
          npm ci
          SHORT_SHA=$(echo $GITHUB_SHA | cut -c1-7)
          npm run build:all
          npm run prepack
          npm run prepareForPublic
          git status
          git add . && git commit -m 'chore: patch package for preview'
          npm version --no-git-tab-version prerelease --preid $SHORT_SHA
          npm publish --tag preview
          git reset HEAD^ && git reset --hard
        shell: bash
